# This file was generated by GoReleaser. DO NOT EDIT.
cask "mless" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "ac3499877491285582a5bb0a843935d82779e4c00c15ad92146d5520e637031b"
      url "https://github.com/TimelordUK/mless/releases/download/v#{version}/mless_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2307b172050be72147cb7bec8e7204e2c77d56a183eb2765bf7dcc46b87cf751"
      url "https://github.com/TimelordUK/mless/releases/download/v#{version}/mless_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d2e5f5f48e7339368eccee660c96278df28f002b198ea9ea1ab521b0c1c2d993"
      url "https://github.com/TimelordUK/mless/releases/download/v#{version}/mless_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2e79d7834dc6876e6f934ca815384f5d9368c46ac4d1916cdb3c6c9aa9e100bd"
      url "https://github.com/TimelordUK/mless/releases/download/v#{version}/mless_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mless"
  desc "A modern log-aware pager for the terminal — less, but for log files."
  homepage "https://github.com/TimelordUK/mless"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mless"

  # No zap stanza required

end
