# This file was generated by GoReleaser. DO NOT EDIT.
cask "mless" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "7470e52e5d82b09954c59391773563a327f0eb4806d0335822e1415e1035bb6b"
      url "https://github.com/TimelordUK/mless/releases/download/v#{version}/mless_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5f835f68b109d1a91aab192841e87af94e623f83158f980d58f6bbb14ce39fda"
      url "https://github.com/TimelordUK/mless/releases/download/v#{version}/mless_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "222d63190aece5c4132df620d88c2b2f6effcb3adbe19494720310945f9dc187"
      url "https://github.com/TimelordUK/mless/releases/download/v#{version}/mless_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ef55585d25b1e7f6565088c560dbb66fa8528a587d582f6c85c38e33cb7e75aa"
      url "https://github.com/TimelordUK/mless/releases/download/v#{version}/mless_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mless"
  desc "A modern log-aware pager for the terminal — less, but for log files."
  homepage "https://github.com/TimelordUK/mless"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mless"

  # No zap stanza required

end
