# This file was generated by GoReleaser. DO NOT EDIT.
cask "mless" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "4d5f0dd4b576ee00f1203f4297bd513fa328a8ff4ec345ee8310c0ea2154fc8c"
      url "https://github.com/TimelordUK/mless/releases/download/v#{version}/mless_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ff7c9cccc94624bd1f7c470eae2d46f156cd63d0fdf302891bafe42bd59f8b7d"
      url "https://github.com/TimelordUK/mless/releases/download/v#{version}/mless_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fe89e52438b66baae459ddca5a2a4fcec87d24000bf15092becf9f9e7819c513"
      url "https://github.com/TimelordUK/mless/releases/download/v#{version}/mless_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8a840fda470330c334ea427d3bb1717e3d11f23892316f9e58d08e07ae1ddbe6"
      url "https://github.com/TimelordUK/mless/releases/download/v#{version}/mless_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mless"
  desc "A modern log-aware pager for the terminal — less, but for log files."
  homepage "https://github.com/TimelordUK/mless"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mless"

  # No zap stanza required

end
